### ISSUE TITLE
I don't know how to have a valid NC program

### ISSUE THREAD

**Issue by tonyteo-git** [Papooch/WasteOptimiser#22]
Hi Papooch,
Could you share folder has NC program valid to learn more about my error (is not a valid NC program), i see it on 'D:\Ondra\Stuff\OneDrive\VUT\DP\moje\gcode' at your pc when read  wasteoptimiser/__main__.py.
Thanks.

**Comment by Papooch** [comment]
Oh wow, I didn't expect anyone to actually use this :) I didn't actually touch it after my graduation and it seems the path is hardcoded in the source for some reason. If I remember correctly, if you point it to a folder with planar `.gcode` files (you'll have to edit the source), they will show up in the GUI. Here are the example files from the [original folder](https://1drv.ms/u/s!AvoOjYw2dyv53Vbibt09Xo4ER1vt?e=S3jE0U)

**Comment by tonyteo-git** [comment]
Thanks again, WasteOptimiser is amazing, I'm a mechatronics student at HCMUT, now, I'm learning more about the nesting algorithm for my final thesis - cnc fabric cutter

**Comment by Papooch** [comment]
@tonyteo-git were you able to make it work? If you'll need some further assistance, feel free to hit me up.

**Comment by optastar** [comment]
Could you share folder thathas NC program at github? I can't get it from onedrive.

**Comment by Papooch** [comment]
I pushed the folder with shapes to github, now the GUI should open with the folder correctly set up #23
